// Generated by tools/generate-sanity-types.cjs from the musora-platform-backend Sanity schema.
// Do not edit by hand; re-run the generator instead.
export type StatsDocument = {
  _id: string
  _type: "stats"
  _createdAt: string
  _updatedAt: string
  _rev: string
  /** Songs Count */
  songs_count?: string
} & (
  | {
      brand: "musora"
      /** Total Student Count */
      total_student_count?: string
    }
  | {
      brand: "drumeo" | "pianote" | "singeo" | "guitareo" | "playbass"
      /** Learning Paths Count */
      learning_paths_count?: string
      /** Artist Courses Count */
      artist_courses_count?: string
    }
)

export type PracticeGoalDocument = {
  _id: string
  _type: "practice-goal"
  _createdAt: string
  _updatedAt: string
  _rev: string
  brand: "drumeo" | "pianote" | "singeo" | "guitareo" | "playbass"
  /** <2 Days a Week */
  under_two_days_a_week?: {
    /** First Day */
    first_day?: string
    /** First Week */
    first_week?: string
    /** First Month */
    first_month?: string
  }
  /** 3-4 Days a Week */
  three_to_four_days_a_week?: {
    /** First Day */
    first_day?: string
    /** First Week */
    first_week?: string
    /** First Month */
    first_month?: string
  }
  /** 5+ Days a Week */
  five_plus_days_a_week?: {
    /** First Day */
    first_day?: string
    /** First Week */
    first_week?: string
    /** First Month */
    first_month?: string
  }
}

export type TestimonialDocument = {
  _id: string
  _type: "testimonial"
  _createdAt: string
  _updatedAt: string
  _rev: string
  brand: "musora" | "drumeo" | "pianote" | "singeo" | "guitareo" | "playbass"
  /** Testimonials */
  testimonials?: {
    _key: string
    name?: string
    location?: string
    /** Testimonial Copy */
    copy?: string
  }[]
}

export type FaqDocument = {
  _id: string
  _type: "faq"
  _createdAt: string
  _updatedAt: string
  _rev: string
  brand: "musora" | "drumeo" | "pianote" | "singeo" | "guitareo" | "playbass"
  /** FAQs */
  questions?: {
    _key: string
    /** Web Only? */
    web_only?: boolean
    question?: string
    answer?: string
  }[]
}
