// Generated by tools/generate-sanity-types.cjs from the musora-platform-backend Sanity schema.
// Do not edit by hand; re-run the generator instead.
export type PortableTextBlock = {
  _type: string
  _key?: string
  style?: string
  listItem?: string
  level?: number
  markDefs?: { _type: string; _key: string; [key: string]: unknown }[]
  children?: { _type: string; _key?: string; text?: string; marks?: string[] }[]
}

export type PublicAnnouncementDocument = {
  _id: string
  _type: "public-announcement"
  _createdAt: string
  _updatedAt: string
  _rev: string
  /** Announcement Title */
  title: string
  slug: { _type: "slug"; current: string }
  /** Announcement Date */
  published_on: string
  /** Announcement Description */
  description: string
  /** Message */
  message: (PortableTextBlock | { _type: "image"; asset: { _type: "reference"; _ref: string } })[]
  /** Notify Users? */
  notify_users?: boolean
  /** Created Forum Threads By Brand */
  forum_data?: {
    /** Drumeo */
    drumeo?: {
      /** Thread ID */
      thread_id?: number
      /** Category ID */
      category_id?: number
      /** URL */
      url?: string
    }
    /** Pianote */
    pianote?: {
      /** Thread ID */
      thread_id?: number
      /** Category ID */
      category_id?: number
      /** URL */
      url?: string
    }
    /** Guitareo */
    guitareo?: {
      /** Thread ID */
      thread_id?: number
      /** Category ID */
      category_id?: number
      /** URL */
      url?: string
    }
    /** Singeo */
    singeo?: {
      /** Thread ID */
      thread_id?: number
      /** Category ID */
      category_id?: number
      /** URL */
      url?: string
    }
    /** PlayBass */
    playbass?: {
      /** Thread ID */
      thread_id?: number
      /** Category ID */
      category_id?: number
      /** URL */
      url?: string
    }
  }
}
