import SyncRepository from "./base";
import ContentPractice from "../models/ContentPractice";
import { RecordId } from "@nozbe/watermelondb";

export default class PracticeRepository extends SyncRepository<ContentPractice> {
  async recordPractice(details: {
    auto: boolean;
    duration_seconds: number;
    content_id?: number;
    title?: string;
  }) {
    // if (details['auto']) {
    //   return await this.upsertOne(PracticeRepository.generateAutoId(details.content_id!, ), r => {
    // }

    return await this.insertOne((r) => {
      const manualId = r._raw.id // yoink watermelon's autogenerated id

      r._raw.id = `manual:${manualId}`;
      r.manual_id = manualId
      r.auto = false;

      r.day = new Date().toLocaleDateString('sv-SE'); // YYYY-MM-DD in user's timezone
      r.duration_seconds = details.duration_seconds;

      r.title = details.title ?? null;
    });
  }

  async updateDetails(id: RecordId, details: {
    duration_seconds: number;
    title: string;
  }) {
    return await this.updateOneId(id, r => {
      r.duration_seconds = details.duration_seconds;
      r.title = details.title;
    })
  }

  private static generateAutoId(contentId: number, day: string) {
    return ['auto', contentId.toString(), day].join(':');
  }
}
