import SyncRepository, { Q } from "./base";
import Practice from "../models/Practice";
import { RecordId } from "@nozbe/watermelondb";

export const generatePracticeSessionId = () => Math.random().toString(36).slice(2, 8)

export default class PracticesRepository extends SyncRepository<Practice> {
  async sumPracticeMinutesForContent(contentIds: number[]): Promise<number> {
    if (contentIds.length === 0) return 0

    const practices = await this.queryAll(
      Q.where('content_id', Q.oneOf(contentIds))
    )

    const totalSeconds = practices.data.reduce(
      (sum, practice) => sum + practice.duration_seconds,
      0
    )

    return Math.round(totalSeconds / 60)
  }

  async trackAutoPractice(contentId: number, date: string, sessionId: string, elapsedSeconds: number, skipPush = true) {
    this.store.log('trackUserPractice:before', {
      now: performance.now(),
      contentId,
      date,
      elapsedSeconds,
      sessionId,
    })

    const result = await this.upsertOne(Practice.generateAutoId(contentId, date), r => {
      const oldDurationSeconds = r.duration_seconds;

      r._raw.id = Practice.generateAutoId(contentId, date);
      r.auto = true;
      r.content_id = contentId;
      r.date = date;

      const sessions = { ...r.session_duration_seconds, [sessionId]: elapsedSeconds }
      r.session_duration_seconds = sessions

      this.store.log('trackUserPractice:around', {
        now: performance.now(),
        contentId,
        date,
        elapsedSeconds,
        sessionId,
        before: oldDurationSeconds,
        after: r.duration_seconds,
      })
    }, { skipPush })

    this.store.log('trackUserPractice:after', {
      now: performance.now(),
      contentId,
      date,
      elapsedSeconds,
      sessionId,
      after: result.data.duration_seconds,
    })

    return result
  }

  async recordManualPractice(date: string, durationSeconds: number, details: Partial<Pick<Practice, 'title' | 'instrument_id' | 'category_id' | 'thumbnail_url'>> = {}) {
    return await this.insertOne((r) => {
      const manualId = r._raw.id; // yoink watermelon's autogenerated id
      r._raw.id = Practice.generateManualId(manualId);

      r.manual_id = manualId;
      r.auto = false;

      r.date = date;
      r.duration_seconds_override = Math.min(durationSeconds, 59999);

      r.title = details.title ?? null;
      r.thumbnail_url = details.thumbnail_url ?? null;
      r.category_id = details.category_id ?? null;
      r.instrument_id = details.instrument_id ?? null;
    });
  }

  async updateDetails(id: RecordId, details: Partial<Pick<Practice, 'duration_seconds_override' | 'title' | 'thumbnail_url' | 'category_id' | 'instrument_id'>>) {
    return await this.updateOneId(id, r => {
      if ('duration_seconds_override' in details) r.duration_seconds_override = details.duration_seconds_override != null ? Math.min(details.duration_seconds_override, 59999) : null
      r.title = details.title ?? r.title;
      r.thumbnail_url = details.thumbnail_url ?? r.thumbnail_url;
      r.category_id = details.category_id ?? r.category_id;
      r.instrument_id = details.instrument_id ?? r.instrument_id;
    })
  }


  async getAutoPracticesOnDate(date: string) {
    return await this.queryAll(
      Q.where('date', date),
      Q.where('auto', true),
      Q.sortBy('created_at', 'asc')
    )
  }
}
