import SyncRepository, { Q } from "./base";
import Practice from "../models/Practice";
import { RecordId } from "@nozbe/watermelondb";

export default class PracticesRepository extends SyncRepository<Practice> {
  async sumPracticeMinutesForContent(contentIds: number[]): Promise<number> {
    if (contentIds.length === 0) return 0

    const practices = await this.queryAll(
      Q.where('content_id', Q.oneOf(contentIds))
    )

    const totalSeconds = practices.data.reduce(
      (sum, practice) => sum + practice.duration_seconds,
      0
    )

    return Math.round(totalSeconds / 60)
  }

  async trackAutoPractice(contentId: number, date: string, incrementalDurationSeconds: number) {
    return await this.upsertOne(PracticesRepository.generateAutoId(contentId, date), r => {
      r._raw.id = PracticesRepository.generateAutoId(contentId, date);
      r.auto = true;
      r.content_id = contentId;
      r.date = date;

      r.duration_seconds = Math.min((r.duration_seconds || 0) + incrementalDurationSeconds, 59999);
    })
  }

  async recordManualPractice(date: string, durationSeconds: number, details: Partial<Pick<Practice, 'title' | 'instrument_id' | 'category_id' | 'thumbnail_url'>> = {}) {
    return await this.insertOne((r) => {
      const manualId = r._raw.id; // yoink watermelon's autogenerated id
      r._raw.id = PracticesRepository.generateManualId(manualId);

      r.manual_id = manualId;
      r.auto = false;

      r.date = date;
      r.duration_seconds = Math.min(durationSeconds, 59999);

      r.title = details.title ?? null;
      r.thumbnail_url = details.thumbnail_url ?? null;
      r.category_id = details.category_id ?? null;
      r.instrument_id = details.instrument_id ?? null;
    });
  }

  async updateDetails(id: RecordId, details: Partial<Pick<Practice, 'duration_seconds' | 'title' | 'thumbnail_url' | 'category_id' | 'instrument_id'>>) {
    return await this.updateOneId(id, r => {
      ['duration_seconds', 'title', 'thumbnail_url', 'category_id', 'instrument_id'].forEach(key => {
        const value = details[key as keyof typeof details];
        if (value !== undefined) {
          (r as any)[key] = value;
        }
      })
    })
  }

  private static generateAutoId(contentId: number, date: string) {
    return ['auto', contentId.toString(), date].join(':');
  }

  private static generateManualId(manualId: string) {
    return `manual:${manualId}`;
  }
}
