/*** This file was generated automatically. To recreate, please run `npm run build-index`. ***/

import {
	globalConfig,
	initializeService
} from './services/config.js';

import {
	enrollUserInGuidedCourse,
	fetchEnrollmentPageMetadata,
	guidedCourses,
	unEnrollUserInGuidedCourse
} from './services/content-org/guided-courses.ts';
import { enrollUserInGuidedCourse, fetchEnrollmentPageMetadata, guidedCourses, pinGuidedCourse, pinnedGuidedCourses, unEnrollUserInGuidedCourse, unPinGuidedCourse } from './services/content-org/guided-courses.ts';

import {
	getContentRows,
	getLessonContentRows,
	getNewAndUpcoming,
	getRecent,
	getRecentForTab,
	getRecommendedForYou,
	getScheduleContentRows,
	getTabResults
} from './services/content.js';

import {
	getContentRows,
	getLessonContentRows,
	getNewAndUpcoming,
	getRecent,
	getRecommendedForYou,
	getScheduleContentRows,
	getTabResults
} from './services/content.js';
import { getContentRows, getLessonContentRows, getNewAndUpcoming, getRecent, getRecentForTab, getRecommendedForYou, getScheduleContentRows, getTabResults } from './services/content.js';

import {
	isContentLiked,
	isContentLikedByIds,
	likeContent,
	unlikeContent
} from './services/contentLikes.js';

import {
	contentStatusCompleted,
	contentStatusReset,
	contentStatusStarted,
	getAllCompleted,
	getAllStarted,
	getAllStartedOrCompleted,
	getLastInteractedOf,
	getNavigateTo,
	getNextLesson,
	getProgressDateByIds,
	getProgressPercentage,
	getProgressPercentageByIds,
	getProgressState,
	getProgressStateByIds,
	getResumeTimeSeconds,
	getResumeTimeSecondsByIds,
	getStartedOrCompletedProgressOnly,
	recordWatchSession
} from './services/contentProgress.js';

import {
	contentStatusCompleted,
	contentStatusReset,
	contentStatusStarted,
	getAllCompleted,
	getAllStarted,
	getAllStartedOrCompleted,
	getLastInteractedOf,
	getNavigateTo,
	getNextLesson,
	getProgressDateByIds,
	getProgressPercentage,
	getProgressPercentageByIds,
	getProgressState,
	getProgressStateByIds,
	getResumeTimeSeconds,
	getResumeTimeSecondsByIds,
	getStartedOrCompletedProgressOnly,
	recordWatchSession
} from './services/contentProgress.js';
import { contentStatusCompleted, contentStatusReset, getAllCompleted, getAllStarted, getAllStartedOrCompleted, getLastInteractedOf, getNavigateTo, getNextLesson, getProgressDateByIds, getProgressPercentage, getProgressPercentageByIds, getProgressState, getProgressStateByIds, getResumeTimeSeconds, getResumeTimeSecondsByIds, getStartedOrCompletedProgressOnly, recordWatchSession } from './services/contentProgress.js';

import {
	convertToTimeZone,
	getMonday,
	getTimeRemainingUntilLocal,
	getWeekNumber,
	isNextDay,
	isSameDate,
	toDayjs
} from './services/dateUtils.js';

import {
	getActiveDiscussions
} from './services/forum.js';

import {
	createForumCategory,
	fetchForumCategories,
	updateForumCategory
} from './services/forums/categories.ts';

import {
	getActiveDiscussions
} from './services/forums/forums.ts';

import {
	createPost,
	deletePost,
	fetchCommunityGuidelines,
	fetchPosts,
	jumpToPost,
	likePost,
	search,
	unlikePost,
	updatePost
} from './services/forums/posts.ts';

import {
	createThread,
	deleteThread,
	fetchFollowedThreads,
	fetchLatestThreads,
	fetchThreads,
	followThread,
	lockThread,
	pinThread,
	unfollowThread,
	unlockThread,
	unpinThread,
	updateThread
} from './services/forums/threads.ts';

import {
	fetchAwardsForUser,
	fetchCertificate,
	getAwardDataForGuidedContent
} from './services/gamification/awards.ts';
import { getActiveDiscussions } from './services/forum.js';

import {
	applyCloudflareWrapper,
	applySanityTransformations,
	buildImageSRC
} from './services/imageSRCBuilder.js';

import {
	extractSanityUrl,
	isBucketUrl,
	verifyImageSRC
} from './services/imageSRCVerify.js';

import {
	assignModeratorToComment,
	closeComment,
	createComment,
	deleteComment,
	editComment,
	fetchAllCompletedStates,
	fetchCarouselCardData,
	fetchComment,
	fetchCommentRelies,
	fetchComments,
	fetchCompletedContent,
	fetchCompletedState,
	fetchContentInProgress,
	fetchContentPageUserData,
	fetchHandler,
	fetchLastInteractedChild,
	fetchLikeCount,
	fetchNextContentDataForParent,
	fetchRecent,
	fetchRecentUserActivities,
	fetchSongsInProgress,
	fetchTopComment,
	fetchUserAward,
	fetchUserBadges,
	fetchUserPermissionsData,
	fetchUserPracticeMeta,
	fetchUserPracticeNotes,
	fetchUserPractices,
	likeComment,
	logUserPractice,
	openComment,
	postContentComplete,
	postContentReset,
	postContentRestore,
	postContentStart,
	postPlaylistContentEngaged,
	replyToComment,
	reportComment,
	restoreComment,
	setStudentViewForUser,
	unassignModeratorToComment,
	unlikeComment
} from './services/railcontent.js';

import {
	assignModeratorToComment,
	closeComment,
	createComment,
	deleteComment,
	editComment,
	fetchAllCompletedStates,
	fetchCarouselCardData,
	fetchComment,
	fetchCommentRelies,
	fetchComments,
	fetchCompletedContent,
	fetchCompletedState,
	fetchContentInProgress,
	fetchContentPageUserData,
	fetchContentProgress,
	fetchHandler,
	fetchLastInteractedChild,
	fetchLikeCount,
	fetchNextContentDataForParent,
	fetchRecentUserActivities,
	fetchSongsInProgress,
	fetchTopComment,
	fetchUserAward,
	fetchUserBadges,
	fetchUserLikes,
	fetchUserPermissionsData,
	fetchUserPracticeMeta,
	fetchUserPracticeNotes,
	fetchUserPractices,
	likeComment,
	logUserPractice,
	openComment,
	postContentComplete,
	postContentLiked,
	postContentReset,
	postContentRestore,
	postContentStart,
	postContentUnliked,
	postPlaylistContentEngaged,
	postRecordWatchSession,
	replyToComment,
	reportComment,
	restoreComment,
	setStudentViewForUser,
	unassignModeratorToComment,
	unlikeComment
} from './services/railcontent.js';
import { assignModeratorToComment, closeComment, createComment, deleteComment, editComment, fetchAllCompletedStates, fetchCarouselCardData, fetchComment, fetchCommentRelies, fetchComments, fetchCompletedContent, fetchCompletedState, fetchContentInProgress, fetchContentPageUserData, fetchContentProgress, fetchHandler, fetchLastInteractedChild, fetchLikeCount, fetchNextContentDataForParent, fetchRecent, fetchRecentUserActivities, fetchSongsInProgress, fetchTopComment, fetchUserAward, fetchUserBadges, fetchUserLikes, fetchUserPermissionsData, fetchUserPracticeMeta, fetchUserPracticeNotes, fetchUserPractices, likeComment, logUserPractice, openComment, postContentComplete, postContentLiked, postContentReset, postContentRestore, postContentUnliked, postPlaylistContentEngaged, postRecordWatchSession, replyToComment, reportComment, restoreComment, setStudentViewForUser, unassignModeratorToComment, unlikeComment } from './services/railcontent.js';

import {
	fetchAll,
	fetchAllFilterOptions,
	fetchAllPacks,
	fetchArtistLessons,
	fetchArtists,
	fetchByRailContentId,
	fetchByRailContentIds,
	fetchByReference,
	fetchChatAndLiveEnvent,
	fetchCoachLessons,
	fetchComingSoon,
	fetchCommentModContentData,
	fetchContentRows,
	fetchFoundation,
	fetchGenreLessons,
	fetchHierarchy,
	fetchLeaving,
	fetchLessonContent,
	fetchLessonsFeaturingThisContent,
	fetchLiveEvent,
	fetchMetadata,
	fetchMethod,
	fetchMethodChildren,
	fetchMethodChildrenIds,
	fetchMethodPreviousNextLesson,
	fetchNewReleases,
	fetchNextPreviousLesson,
	fetchOtherSongVersions,
	fetchPackAll,
	fetchPackData,
	fetchParentForDownload,
	fetchPlayAlongsCount,
	fetchRelatedLessons,
	fetchRelatedRecommendedContent,
	fetchRelatedSongs,
	fetchReturning,
	fetchSanity,
	fetchScheduledAndNewReleases,
	fetchScheduledReleases,
	fetchShows,
	fetchShowsData,
	fetchSiblingContent,
	fetchSongArtistCount,
	fetchSongById,
	fetchTabData,
	fetchTopLevelParentId,
	fetchUpcomingEvents,
	getSortOrder,
	jumpToContinueContent
} from './services/sanity.js';

import {
	fetchAll,
	fetchAllFilterOptions,
	fetchAllPacks,
	fetchArtistLessons,
	fetchArtists,
	fetchByRailContentId,
	fetchByRailContentIds,
	fetchByReference,
	fetchChatAndLiveEnvent,
	fetchCoachLessons,
	fetchComingSoon,
	fetchCommentModContentData,
	fetchContentRows,
	fetchFoundation,
	fetchGenreLessons,
	fetchHierarchy,
	fetchLeaving,
	fetchLessonContent,
	fetchLessonsFeaturingThisContent,
	fetchLiveEvent,
	fetchMetadata,
	fetchMethod,
	fetchMethodChildren,
	fetchMethodChildrenIds,
	fetchMethodPreviousNextLesson,
	fetchNewReleases,
	fetchNextPreviousLesson,
	fetchOtherSongVersions,
	fetchPackAll,
	fetchPackData,
	fetchPlayAlongsCount,
	fetchRecent,
	fetchRelatedLessons,
	fetchRelatedRecommendedContent,
	fetchRelatedSongs,
	fetchReturning,
	fetchSanity,
	fetchScheduledAndNewReleases,
	fetchScheduledReleases,
	fetchShows,
	fetchShowsData,
	fetchSiblingContent,
	fetchSongArtistCount,
	fetchSongById,
	fetchTabData,
	fetchTopLevelParentId,
	fetchUpcomingEvents,
	getSortOrder,
	jumpToContinueContent
} from './services/sanity.js';

import {
	confirmEmailChange,
	deleteAccount,
	requestEmailChange,
	resetPassword,
	sendAccountSetupEmail,
	sendPasswordResetEmail,
	setupAccount,
	status
} from './services/user/account.ts';
import { fetchAll, fetchAllFilterOptions, fetchAllPacks, fetchArtistLessons, fetchArtists, fetchByRailContentId, fetchByRailContentIds, fetchByReference, fetchChatAndLiveEnvent, fetchCoachLessons, fetchComingSoon, fetchCommentModContentData, fetchContentRows, fetchFoundation, fetchGenreLessons, fetchHierarchy, fetchLeaving, fetchLessonContent, fetchLessonsFeaturingThisContent, fetchLiveEvent, fetchMetadata, fetchMethod, fetchMethodChildren, fetchMethodChildrenIds, fetchMethodPreviousNextLesson, fetchNewReleases, fetchNextPreviousLesson, fetchOtherSongVersions, fetchPackAll, fetchPackData, fetchParentForDownload, fetchPlayAlongsCount, fetchRelatedLessons, fetchRelatedRecommendedContent, fetchRelatedSongs, fetchReturning, fetchSanity, fetchScheduledAndNewReleases, fetchScheduledReleases, fetchShows, fetchShowsData, fetchSiblingContent, fetchSongArtistCount, fetchSongById, fetchTabData, fetchTopLevelParentId, fetchUpcomingEvents, getSortOrder, jumpToContinueContent } from './services/sanity.js';

import {
	fetchInterests,
	fetchUninterests,
	markContentAsInterested,
	markContentAsNotInterested,
	removeContentAsInterested,
	removeContentAsNotInterested
} from './services/user/interests.js';

import {
	blockUser,
	deletePicture,
	getUserData,
	unblockUser,
	uploadPicture,
	uploadPictureFromS3
} from './services/user/management.js';

import {
	deleteNotification,
	fetchLiveEventPollingState,
	fetchNotificationSettings,
	fetchNotifications,
	fetchUnreadCount,
	markAllNotificationsAsRead,
	markNotificationAsRead,
	markNotificationAsUnread,
	pauseLiveEventPolling,
	restoreNotification,
	startLiveEventPolling,
	updateNotificationSetting
} from './services/user/notifications.js';

import {
	blockUser,
	blockedUsers,
	deletePicture,
	getUserData,
	getUserSignature,
	isUsernameAvailable,
	setUserSignature,
	toggleSignaturePrivate,
	unblockUser,
	updateDisplayName,
	uploadPicture,
	uploadPictureFromS3
} from './services/user/management.js';

import {
	fetchMemberships,
	fetchRechargeTokens,
	restorePurchases,
	upgradeSubscription
} from './services/user/memberships.ts';

import {
	deleteNotification,
	fetchLiveEventPollingState,
	fetchNotificationSettings,
	fetchNotifications,
	fetchUnreadCount,
	markAllNotificationsAsRead,
	markNotificationAsRead,
	markNotificationAsUnread,
	pauseLiveEventPolling,
	restoreNotification,
	startLiveEventPolling,
	updateNotificationSetting
} from './services/user/notifications.js';

import {
	startOnboarding
} from './services/user/onboarding.ts';

import {
	fetchCustomerPayments
} from './services/user/payments.ts';

import {
	fetchUserPermissions,
	reset
} from './services/user/permissions.js';
import syncDatabaseFactory from './services/sync/database/factory.ts';

import {
	deleteProfilePicture,
	otherStats
} from './services/user/profile.js';

import {
	login,
	logout
} from './services/user/sessions.js';

import {
	calculateLongestStreaks,
	createPracticeNotes,
	deletePracticeSession,
	deleteUserActivity,
	fetchRecentActivitiesActiveTabs,
	findIncompleteLesson,
	getPracticeNotes,
	getPracticeSessions,
	getProgressRows,
	getRecentActivity,
	getUserMonthlyStats,
	getUserPractices,
	getUserWeeklyStats,
	pinProgressRow,
	recordUserActivity,
	recordUserPractice,
	removeUserPractice,
	restorePracticeSession,
	restoreUserActivity,
	restoreUserPractice,
	unpinProgressRow,
	updatePracticeNotes,
	updateUserPractice
} from './services/userActivity.js';

import {
	 default as EventsAPI
} from './services/eventsAPI';

declare module 'musora-content-services' {
	export {
		addContextToContent,
		addItemToPlaylist,
		applyCloudflareWrapper,
		applySanityTransformations,
		assignModeratorToComment,
		blockUser,
		blockedUsers,
		buildImageSRC,
		calculateLongestStreaks,
		closeComment,
		confirmEmailChange,
		contentStatusCompleted,
		contentStatusReset,
		contentStatusStarted,
		convertToTimeZone,
		createComment,
		createForumCategory,
		createPlaylist,
		createPost,
		createPracticeNotes,
		createThread,
		deleteAccount,
		deleteComment,
		deleteItemsFromPlaylist,
		deleteNotification,
		deletePicture,
		deletePlaylist,
		deletePost,
		deletePracticeSession,
		deleteProfilePicture,
		deleteThread,
		deleteUserActivity,
		duplicatePlaylist,
		editComment,
		enrollUserInGuidedCourse,
		extractSanityUrl,
		fetchAll,
		fetchAllCompletedStates,
		fetchAllFilterOptions,
		fetchAllPacks,
		fetchArtistLessons,
		fetchArtists,
		fetchAwardsForUser,
		fetchByRailContentId,
		fetchByRailContentIds,
		fetchByReference,
		fetchCarouselCardData,
		fetchCertificate,
		fetchChatAndLiveEnvent,
		fetchChatSettings,
		fetchCoachLessons,
		fetchComingSoon,
		fetchComment,
		fetchCommentModContentData,
		fetchCommentRelies,
		fetchComments,
		fetchCommunityGuidelines,
		fetchCompletedContent,
		fetchCompletedState,
		fetchContentInProgress,
		fetchContentPageUserData,
		fetchContentRows,
		fetchCustomerPayments,
		fetchEnrollmentPageMetadata,
		fetchFollowedThreads,
		fetchForumCategories,
		fetchFoundation,
		fetchGenreLessons,
		fetchHandler,
		fetchHierarchy,
		fetchInterests,
		fetchLastInteractedChild,
		fetchLatestThreads,
		fetchLeaving,
		fetchLessonContent,
		fetchLessonsFeaturingThisContent,
		fetchLikeCount,
		fetchLiveEvent,
		fetchLiveEventPollingState,
		fetchMemberships,
		fetchMetadata,
		fetchMethod,
		fetchMethodChildren,
		fetchMethodChildrenIds,
		fetchMethodPreviousNextLesson,
		fetchNewReleases,
		fetchNextContentDataForParent,
		fetchNextPreviousLesson,
		fetchNotificationSettings,
		fetchNotifications,
		fetchOtherSongVersions,
		fetchPackAll,
		fetchPackData,
		fetchPlayAlongsCount,
		fetchPlaylist,
		fetchPlaylistItems,
		fetchPosts,
		fetchRecent,
		fetchRecentActivitiesActiveTabs,
		fetchRecentUserActivities,
		fetchRechargeTokens,
		fetchRelatedLessons,
		fetchRelatedRecommendedContent,
		fetchRelatedSongs,
		fetchReturning,
		fetchSanity,
		fetchScheduledAndNewReleases,
		fetchScheduledReleases,
		fetchShows,
		fetchShowsData,
		fetchSiblingContent,
		fetchSimilarItems,
		fetchSongArtistCount,
		fetchSongById,
		fetchSongsInProgress,
		fetchTabData,
		fetchThreads,
		fetchTopComment,
		fetchTopLevelParentId,
		fetchUninterests,
		fetchUnreadCount,
		fetchUpcomingEvents,
		fetchUserAward,
		fetchUserBadges,
		fetchUserPermissions,
		fetchUserPermissionsData,
		fetchUserPlaylists,
		fetchUserPracticeMeta,
		fetchUserPracticeNotes,
		fetchUserPractices,
		findIncompleteLesson,
		followThread,
		getActiveDiscussions,
		getAllCompleted,
		getAllStarted,
		getAllStartedOrCompleted,
		getAwardDataForGuidedContent,
		getContentRows,
		getLastInteractedOf,
		getLessonContentRows,
		getMonday,
		getNavigateTo,
		getNavigateToForPlaylists,
		getNewAndUpcoming,
		getNextLesson,
		getPracticeNotes,
		getPracticeSessions,
		getProgressDateByIds,
		getProgressPercentage,
		getProgressPercentageByIds,
		getProgressRows,
		getProgressState,
		getProgressStateByIds,
		getRecent,
		getRecentActivity,
		getRecommendedForYou,
		getResumeTimeSeconds,
		getResumeTimeSecondsByIds,
		getScheduleContentRows,
		getSortOrder,
		getStartedOrCompletedProgressOnly,
		getTabResults,
		getTimeRemainingUntilLocal,
		getUserData,
		getUserMonthlyStats,
		getUserPractices,
		getUserSignature,
		getUserWeeklyStats,
		getWeekNumber,
		globalConfig,
		guidedCourses,
		initializeService,
		isBucketUrl,
		isContentLiked,
		isContentLikedByIds,
		isNextDay,
		isSameDate,
		isUsernameAvailable,
		jumpToContinueContent,
		jumpToPost,
		likeComment,
		likeContent,
		likePlaylist,
		likePost,
		lockThread,
		logUserPractice,
		login,
		logout,
		markAllNotificationsAsRead,
		markContentAsInterested,
		markContentAsNotInterested,
		markNotificationAsRead,
		markNotificationAsUnread,
		openComment,
		otherStats,
		pauseLiveEventPolling,
		pinProgressRow,
		pinThread,
		postContentComplete,
		postContentReset,
		postContentRestore,
		postContentStart,
		postContentUnliked,
		postPlaylistContentEngaged,
		rankCategories,
		rankItems,
		recommendations,
		recordUserActivity,
		recordUserPractice,
		recordWatchSession,
		removeContentAsInterested,
		removeContentAsNotInterested,
		removeUserPractice,
		replyToComment,
		reportComment,
		reportPlaylist,
		requestEmailChange,
		reset,
		resetPassword,
		restoreComment,
		restoreItemFromPlaylist,
		restoreNotification,
		restorePracticeSession,
		restorePurchases,
		restoreUserActivity,
		restoreUserPractice,
		search,
		sendAccountSetupEmail,
		sendPasswordResetEmail,
		setStudentViewForUser,
		setUserSignature,
		setupAccount,
		startLiveEventPolling,
		startOnboarding,
		status,
		syncPull,
		syncPush,
		toDayjs,
		togglePlaylistPrivate,
		toggleSignaturePrivate,
		unEnrollUserInGuidedCourse,
		unassignModeratorToComment,
		unblockUser,
		undeletePlaylist,
		unfollowThread,
		unlikeComment,
		unlikeContent,
		unlikePlaylist,
		unlikePost,
		unlockThread,
		unpinProgressRow,
		unpinThread,
		updateDisplayName,
		updateForumCategory,
		updateNotificationSetting,
		updatePlaylist,
		updatePost,
		updatePracticeNotes,
		updateThread,
		updateUserPractice,
		upgradeSubscription,
		uploadPicture,
		uploadPictureFromS3,
		verifyImageSRC,
		verifyLocalDataContext,
	}
}

export default EventsAPI
