name: Sync README to Mintlify Docs

on:
  push:
    paths: [ 'README.md' ]

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Mintlify docs repository
        uses: actions/checkout@v4
        with:
          repository: railroadmedia/documentation
          ref: main
          token: ${{ secrets.ORG_DOCS_SYNC_TOKEN }}
          path: mintlify-docs
          persist-credentials: true

      - name: Copy README to docs
        run: |
          mkdir -p mintlify-docs/docs/repositories
          # Extract repo name and create title
          REPO_NAME="${{ github.event.repository.name }}"
          REPO_TITLE=$(echo "$REPO_NAME" | sed 's/-/ /g' | sed 's/\b\w/\U&/g')

          # Add frontmatter and copy content
          cat > mintlify-docs/docs/repositories/${REPO_NAME}.mdx << EOF
          ---
          title: "${REPO_TITLE}"
          description: "Repository documentation for ${REPO_NAME}"
          ---

          EOF
          cat README.md >> mintlify-docs/docs/repositories/${REPO_NAME}.mdx

      - name: Commit and push changes
        working-directory: mintlify-docs
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/repositories/${REPO_NAME}.mdx
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update ${REPO_NAME} documentation from source repo"
            git push
          fi
